/* 
 * CitrineOS Central System API
 *
 * Central System API for OCPP 2.0.1 messaging.
 *
 * OpenAPI spec version: 1.4.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using ocpp.citrineos.Client;
using ocpp.citrineos.Api;
using ocpp.citrineos.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ConfigurationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ConfigurationApiTests
    {
        private ConfigurationApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ConfigurationApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ConfigurationApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ConfigurationApi
            //Assert.IsInstanceOfType(typeof(ConfigurationApi), instance, "instance is a ConfigurationApi");
        }

        /// <summary>
        /// Test DataConfigurationSystemConfigGet
        /// </summary>
        [Test]
        public void DataConfigurationSystemConfigGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.DataConfigurationSystemConfigGet();
            
        }
        /// <summary>
        /// Test DataConfigurationSystemConfigPut
        /// </summary>
        [Test]
        public void DataConfigurationSystemConfigPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.DataConfigurationSystemConfigPut();
            
        }
        /// <summary>
        /// Test OcppConfigurationChangeAvailabilityPost
        /// </summary>
        [Test]
        public void OcppConfigurationChangeAvailabilityPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ConfigurationChangeAvailabilityBody body = null;
            //string identifier = null;
            //string tenantId = null;
            //string callbackUrl = null;
            //instance.OcppConfigurationChangeAvailabilityPost(body, identifier, tenantId, callbackUrl);
            
        }
        /// <summary>
        /// Test OcppConfigurationClearDisplayMessagePost
        /// </summary>
        [Test]
        public void OcppConfigurationClearDisplayMessagePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ConfigurationClearDisplayMessageBody body = null;
            //string identifier = null;
            //string tenantId = null;
            //string callbackUrl = null;
            //instance.OcppConfigurationClearDisplayMessagePost(body, identifier, tenantId, callbackUrl);
            
        }
        /// <summary>
        /// Test OcppConfigurationGetDisplayMessagesPost
        /// </summary>
        [Test]
        public void OcppConfigurationGetDisplayMessagesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ConfigurationGetDisplayMessagesBody body = null;
            //string identifier = null;
            //string tenantId = null;
            //string callbackUrl = null;
            //instance.OcppConfigurationGetDisplayMessagesPost(body, identifier, tenantId, callbackUrl);
            
        }
        /// <summary>
        /// Test OcppConfigurationPublishFirmwarePost
        /// </summary>
        [Test]
        public void OcppConfigurationPublishFirmwarePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ConfigurationPublishFirmwareBody body = null;
            //string identifier = null;
            //string tenantId = null;
            //string callbackUrl = null;
            //instance.OcppConfigurationPublishFirmwarePost(body, identifier, tenantId, callbackUrl);
            
        }
        /// <summary>
        /// Test OcppConfigurationResetPost
        /// </summary>
        [Test]
        public void OcppConfigurationResetPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ConfigurationResetBody body = null;
            //string identifier = null;
            //string tenantId = null;
            //string callbackUrl = null;
            //instance.OcppConfigurationResetPost(body, identifier, tenantId, callbackUrl);
            
        }
        /// <summary>
        /// Test OcppConfigurationSetDisplayMessagePost
        /// </summary>
        [Test]
        public void OcppConfigurationSetDisplayMessagePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ConfigurationSetDisplayMessageBody body = null;
            //string identifier = null;
            //string tenantId = null;
            //string callbackUrl = null;
            //instance.OcppConfigurationSetDisplayMessagePost(body, identifier, tenantId, callbackUrl);
            
        }
        /// <summary>
        /// Test OcppConfigurationSetNetworkProfilePost
        /// </summary>
        [Test]
        public void OcppConfigurationSetNetworkProfilePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ConfigurationSetNetworkProfileBody body = null;
            //string identifier = null;
            //string tenantId = null;
            //string callbackUrl = null;
            //instance.OcppConfigurationSetNetworkProfilePost(body, identifier, tenantId, callbackUrl);
            
        }
        /// <summary>
        /// Test OcppConfigurationTriggerMessagePost
        /// </summary>
        [Test]
        public void OcppConfigurationTriggerMessagePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ConfigurationTriggerMessageBody body = null;
            //string identifier = null;
            //string tenantId = null;
            //string callbackUrl = null;
            //instance.OcppConfigurationTriggerMessagePost(body, identifier, tenantId, callbackUrl);
            
        }
        /// <summary>
        /// Test OcppConfigurationUnpublishFirmwarePost
        /// </summary>
        [Test]
        public void OcppConfigurationUnpublishFirmwarePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ConfigurationUnpublishFirmwareBody body = null;
            //string identifier = null;
            //string tenantId = null;
            //string callbackUrl = null;
            //instance.OcppConfigurationUnpublishFirmwarePost(body, identifier, tenantId, callbackUrl);
            
        }
        /// <summary>
        /// Test OcppConfigurationUpdateFirmwarePost
        /// </summary>
        [Test]
        public void OcppConfigurationUpdateFirmwarePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ConfigurationUpdateFirmwareBody body = null;
            //string identifier = null;
            //string tenantId = null;
            //string callbackUrl = null;
            //instance.OcppConfigurationUpdateFirmwarePost(body, identifier, tenantId, callbackUrl);
            
        }
    }

}
