/* 
 * MaEVe CSMS
 *
 * Internal API to interact with the MaEVe CSMS, external clients should use OCPI.
 *
 * OpenAPI spec version: 0.0.0
 * Contact: maeve-team@thoughtworks.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Connector
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ConnectorTests
    {
        // TODO uncomment below to declare an instance variable for Connector
        //private Connector instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Connector
            //instance = new Connector();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Connector
        /// </summary>
        [Test]
        public void ConnectorInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Connector
            //Assert.IsInstanceOfType<Connector> (instance, "variable 'instance' is a Connector");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Standard'
        /// </summary>
        [Test]
        public void StandardTest()
        {
            // TODO unit test for the property 'Standard'
        }
        /// <summary>
        /// Test the property 'Format'
        /// </summary>
        [Test]
        public void FormatTest()
        {
            // TODO unit test for the property 'Format'
        }
        /// <summary>
        /// Test the property 'PowerType'
        /// </summary>
        [Test]
        public void PowerTypeTest()
        {
            // TODO unit test for the property 'PowerType'
        }
        /// <summary>
        /// Test the property 'MaxVoltage'
        /// </summary>
        [Test]
        public void MaxVoltageTest()
        {
            // TODO unit test for the property 'MaxVoltage'
        }
        /// <summary>
        /// Test the property 'MaxAmperage'
        /// </summary>
        [Test]
        public void MaxAmperageTest()
        {
            // TODO unit test for the property 'MaxAmperage'
        }

    }

}
