/* 
 * CitrineOS Central System API
 *
 * Central System API for OCPP 2.0.1 messaging.
 *
 * OpenAPI spec version: 1.4.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using ocpp.citrineos.Client;
using ocpp.citrineos.Api;
using ocpp.citrineos.Model;

namespace ocpp.citrineos.Test
{
    /// <summary>
    ///  Class for testing EvdriverApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class EvdriverApiTests
    {
        private EvdriverApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new EvdriverApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EvdriverApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' EvdriverApi
            //Assert.IsInstanceOfType(typeof(EvdriverApi), instance, "instance is a EvdriverApi");
        }

        /// <summary>
        /// Test DataEvdriverSystemConfigGet
        /// </summary>
        [Test]
        public void DataEvdriverSystemConfigGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.DataEvdriverSystemConfigGet();
            
        }
        /// <summary>
        /// Test DataEvdriverSystemConfigPut
        /// </summary>
        [Test]
        public void DataEvdriverSystemConfigPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.DataEvdriverSystemConfigPut();
            
        }
        /// <summary>
        /// Test OcppEvdriverCancelReservationPost
        /// </summary>
        [Test]
        public void OcppEvdriverCancelReservationPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //EvdriverCancelReservationBody body = null;
            //string identifier = null;
            //string tenantId = null;
            //string callbackUrl = null;
            //instance.OcppEvdriverCancelReservationPost(body, identifier, tenantId, callbackUrl);
            
        }
        /// <summary>
        /// Test OcppEvdriverClearCachePost
        /// </summary>
        [Test]
        public void OcppEvdriverClearCachePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string identifier = null;
            //string tenantId = null;
            //EvdriverClearCacheBody body = null;
            //string callbackUrl = null;
            //instance.OcppEvdriverClearCachePost(identifier, tenantId, body, callbackUrl);
            
        }
        /// <summary>
        /// Test OcppEvdriverGetLocalListVersionPost
        /// </summary>
        [Test]
        public void OcppEvdriverGetLocalListVersionPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string identifier = null;
            //string tenantId = null;
            //EvdriverGetLocalListVersionBody body = null;
            //string callbackUrl = null;
            //instance.OcppEvdriverGetLocalListVersionPost(identifier, tenantId, body, callbackUrl);
            
        }
        /// <summary>
        /// Test OcppEvdriverRequestStartTransactionPost
        /// </summary>
        [Test]
        public void OcppEvdriverRequestStartTransactionPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //EvdriverRequestStartTransactionBody body = null;
            //string identifier = null;
            //string tenantId = null;
            //string callbackUrl = null;
            //instance.OcppEvdriverRequestStartTransactionPost(body, identifier, tenantId, callbackUrl);
            
        }
        /// <summary>
        /// Test OcppEvdriverRequestStopTransactionPost
        /// </summary>
        [Test]
        public void OcppEvdriverRequestStopTransactionPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //EvdriverRequestStopTransactionBody body = null;
            //string identifier = null;
            //string tenantId = null;
            //string callbackUrl = null;
            //instance.OcppEvdriverRequestStopTransactionPost(body, identifier, tenantId, callbackUrl);
            
        }
        /// <summary>
        /// Test OcppEvdriverReserveNowPost
        /// </summary>
        [Test]
        public void OcppEvdriverReserveNowPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //EvdriverReserveNowBody body = null;
            //string identifier = null;
            //string tenantId = null;
            //string callbackUrl = null;
            //instance.OcppEvdriverReserveNowPost(body, identifier, tenantId, callbackUrl);
            
        }
        /// <summary>
        /// Test OcppEvdriverSendLocalListPost
        /// </summary>
        [Test]
        public void OcppEvdriverSendLocalListPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //EvdriverSendLocalListBody body = null;
            //string identifier = null;
            //string tenantId = null;
            //string callbackUrl = null;
            //instance.OcppEvdriverSendLocalListPost(body, identifier, tenantId, callbackUrl);
            
        }
        /// <summary>
        /// Test OcppEvdriverUnlockConnectorPost
        /// </summary>
        [Test]
        public void OcppEvdriverUnlockConnectorPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //EvdriverUnlockConnectorBody body = null;
            //string identifier = null;
            //string tenantId = null;
            //string callbackUrl = null;
            //instance.OcppEvdriverUnlockConnectorPost(body, identifier, tenantId, callbackUrl);
            
        }
    }

}
