/* 
 * CitrineOS Central System API
 *
 * Central System API for OCPP 2.0.1 messaging.
 *
 * OpenAPI spec version: 1.4.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using ocpp.citrineos.Client;
using ocpp.citrineos.Api;
using ocpp.citrineos.Model;

namespace ocpp.citrineos.Test
{
    /// <summary>
    ///  Class for testing ReportingApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ReportingApiTests
    {
        private ReportingApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ReportingApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReportingApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ReportingApi
            //Assert.IsInstanceOfType(typeof(ReportingApi), instance, "instance is a ReportingApi");
        }

        /// <summary>
        /// Test DataReportingSystemConfigGet
        /// </summary>
        [Test]
        public void DataReportingSystemConfigGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.DataReportingSystemConfigGet();
            
        }
        /// <summary>
        /// Test DataReportingSystemConfigPut
        /// </summary>
        [Test]
        public void DataReportingSystemConfigPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.DataReportingSystemConfigPut();
            
        }
        /// <summary>
        /// Test OcppReportingCustomerInformationPost
        /// </summary>
        [Test]
        public void OcppReportingCustomerInformationPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ReportingCustomerInformationBody body = null;
            //string identifier = null;
            //string tenantId = null;
            //string callbackUrl = null;
            //instance.OcppReportingCustomerInformationPost(body, identifier, tenantId, callbackUrl);
            
        }
        /// <summary>
        /// Test OcppReportingGetBaseReportPost
        /// </summary>
        [Test]
        public void OcppReportingGetBaseReportPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ReportingGetBaseReportBody body = null;
            //string identifier = null;
            //string tenantId = null;
            //string callbackUrl = null;
            //instance.OcppReportingGetBaseReportPost(body, identifier, tenantId, callbackUrl);
            
        }
        /// <summary>
        /// Test OcppReportingGetLogPost
        /// </summary>
        [Test]
        public void OcppReportingGetLogPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ReportingGetLogBody body = null;
            //string identifier = null;
            //string tenantId = null;
            //string callbackUrl = null;
            //instance.OcppReportingGetLogPost(body, identifier, tenantId, callbackUrl);
            
        }
        /// <summary>
        /// Test OcppReportingGetMonitoringReportPost
        /// </summary>
        [Test]
        public void OcppReportingGetMonitoringReportPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ReportingGetMonitoringReportBody body = null;
            //string identifier = null;
            //string tenantId = null;
            //string callbackUrl = null;
            //instance.OcppReportingGetMonitoringReportPost(body, identifier, tenantId, callbackUrl);
            
        }
        /// <summary>
        /// Test OcppReportingGetReportPost
        /// </summary>
        [Test]
        public void OcppReportingGetReportPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ReportingGetReportBody body = null;
            //string identifier = null;
            //string tenantId = null;
            //string callbackUrl = null;
            //instance.OcppReportingGetReportPost(body, identifier, tenantId, callbackUrl);
            
        }
    }

}
