/* 
 * CitrineOS Central System API
 *
 * Central System API for OCPP 2.0.1 messaging.
 *
 * OpenAPI spec version: 1.4.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ocpp.citrineos.Client.SwaggerDateConverter;
namespace ocpp.citrineos.Model
{
    /// <summary>
    /// ConfigurationChangeAvailabilityBody
    /// </summary>
    [DataContract]
        public partial class ConfigurationChangeAvailabilityBody :  IEquatable<ConfigurationChangeAvailabilityBody>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigurationChangeAvailabilityBody" /> class.
        /// </summary>
        /// <param name="customData">customData.</param>
        /// <param name="evse">evse.</param>
        /// <param name="operationalStatus">operationalStatus (required).</param>
        public ConfigurationChangeAvailabilityBody(CustomDataType customData = default(CustomDataType), EVSEType evse = default(EVSEType), OperationalStatusEnumType operationalStatus = default(OperationalStatusEnumType))
        {
            // to ensure "operationalStatus" is required (not null)
            if (operationalStatus == null)
            {
                throw new InvalidDataException("operationalStatus is a required property for ConfigurationChangeAvailabilityBody and cannot be null");
            }
            else
            {
                this.OperationalStatus = operationalStatus;
            }
            this.CustomData = customData;
            this.Evse = evse;
        }
        
        /// <summary>
        /// Gets or Sets CustomData
        /// </summary>
        [DataMember(Name="customData", EmitDefaultValue=false)]
        public CustomDataType CustomData { get; set; }

        /// <summary>
        /// Gets or Sets Evse
        /// </summary>
        [DataMember(Name="evse", EmitDefaultValue=false)]
        public EVSEType Evse { get; set; }

        /// <summary>
        /// Gets or Sets OperationalStatus
        /// </summary>
        [DataMember(Name="operationalStatus", EmitDefaultValue=false)]
        public OperationalStatusEnumType OperationalStatus { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ConfigurationChangeAvailabilityBody {\n");
            sb.Append("  CustomData: ").Append(CustomData).Append("\n");
            sb.Append("  Evse: ").Append(Evse).Append("\n");
            sb.Append("  OperationalStatus: ").Append(OperationalStatus).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ConfigurationChangeAvailabilityBody);
        }

        /// <summary>
        /// Returns true if ConfigurationChangeAvailabilityBody instances are equal
        /// </summary>
        /// <param name="input">Instance of ConfigurationChangeAvailabilityBody to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ConfigurationChangeAvailabilityBody input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CustomData == input.CustomData ||
                    (this.CustomData != null &&
                    this.CustomData.Equals(input.CustomData))
                ) && 
                (
                    this.Evse == input.Evse ||
                    (this.Evse != null &&
                    this.Evse.Equals(input.Evse))
                ) && 
                (
                    this.OperationalStatus == input.OperationalStatus ||
                    (this.OperationalStatus != null &&
                    this.OperationalStatus.Equals(input.OperationalStatus))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CustomData != null)
                    hashCode = hashCode * 59 + this.CustomData.GetHashCode();
                if (this.Evse != null)
                    hashCode = hashCode * 59 + this.Evse.GetHashCode();
                if (this.OperationalStatus != null)
                    hashCode = hashCode * 59 + this.OperationalStatus.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
