/* 
 * CitrineOS Central System API
 *
 * Central System API for OCPP 2.0.1 messaging.
 *
 * OpenAPI spec version: 1.4.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ocpp.citrineos.Client.SwaggerDateConverter;
namespace ocpp.citrineos.Model
{
    /// <summary>
    /// MonitoringSetMonitoringBaseBody
    /// </summary>
    [DataContract]
        public partial class MonitoringSetMonitoringBaseBody :  IEquatable<MonitoringSetMonitoringBaseBody>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MonitoringSetMonitoringBaseBody" /> class.
        /// </summary>
        /// <param name="customData">customData.</param>
        /// <param name="monitoringBase">monitoringBase (required).</param>
        public MonitoringSetMonitoringBaseBody(CustomDataType customData = default(CustomDataType), MonitoringBaseEnumType monitoringBase = default(MonitoringBaseEnumType))
        {
            // to ensure "monitoringBase" is required (not null)
            if (monitoringBase == null)
            {
                throw new InvalidDataException("monitoringBase is a required property for MonitoringSetMonitoringBaseBody and cannot be null");
            }
            else
            {
                this.MonitoringBase = monitoringBase;
            }
            this.CustomData = customData;
        }
        
        /// <summary>
        /// Gets or Sets CustomData
        /// </summary>
        [DataMember(Name="customData", EmitDefaultValue=false)]
        public CustomDataType CustomData { get; set; }

        /// <summary>
        /// Gets or Sets MonitoringBase
        /// </summary>
        [DataMember(Name="monitoringBase", EmitDefaultValue=false)]
        public MonitoringBaseEnumType MonitoringBase { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MonitoringSetMonitoringBaseBody {\n");
            sb.Append("  CustomData: ").Append(CustomData).Append("\n");
            sb.Append("  MonitoringBase: ").Append(MonitoringBase).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MonitoringSetMonitoringBaseBody);
        }

        /// <summary>
        /// Returns true if MonitoringSetMonitoringBaseBody instances are equal
        /// </summary>
        /// <param name="input">Instance of MonitoringSetMonitoringBaseBody to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MonitoringSetMonitoringBaseBody input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CustomData == input.CustomData ||
                    (this.CustomData != null &&
                    this.CustomData.Equals(input.CustomData))
                ) && 
                (
                    this.MonitoringBase == input.MonitoringBase ||
                    (this.MonitoringBase != null &&
                    this.MonitoringBase.Equals(input.MonitoringBase))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CustomData != null)
                    hashCode = hashCode * 59 + this.CustomData.GetHashCode();
                if (this.MonitoringBase != null)
                    hashCode = hashCode * 59 + this.MonitoringBase.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
