/* 
 * CitrineOS Central System API
 *
 * Central System API for OCPP 2.0.1 messaging.
 *
 * OpenAPI spec version: 1.4.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// MonitoringSetMonitoringLevelBody
    /// </summary>
    [DataContract]
        public partial class MonitoringSetMonitoringLevelBody :  IEquatable<MonitoringSetMonitoringLevelBody>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MonitoringSetMonitoringLevelBody" /> class.
        /// </summary>
        /// <param name="customData">customData.</param>
        /// <param name="severity">The Charging Station SHALL only report events with a severity number lower than or equal to this severity.  The severity range is 0-9, with 0 as the highest and 9 as the lowest severity level.    The severity levels have the following meaning: +  *0-Danger* +  Indicates lives are potentially in danger. Urgent attention is needed and action should be taken immediately. +  *1-Hardware Failure* +  Indicates that the Charging Station is unable to continue regular operations due to Hardware issues. Action is required. +  *2-System Failure* +  Indicates that the Charging Station is unable to continue regular operations due to software or minor hardware issues. Action is required. +  *3-Critical* +  Indicates a critical error. Action is required. +  *4-Error* +  Indicates a non-urgent error. Action is required. +  *5-Alert* +  Indicates an alert event. Default severity for any type of monitoring event.  +  *6-Warning* +  Indicates a warning event. Action may be required. +  *7-Notice* +  Indicates an unusual event. No immediate action is required. +  *8-Informational* +  Indicates a regular operational event. May be used for reporting, measuring throughput, etc. No action is required. +  *9-Debug* +  Indicates information useful to developers for debugging, not useful during operations.       (required).</param>
        public MonitoringSetMonitoringLevelBody(CustomDataType customData = default(CustomDataType), int? severity = default(int?))
        {
            // to ensure "severity" is required (not null)
            if (severity == null)
            {
                throw new InvalidDataException("severity is a required property for MonitoringSetMonitoringLevelBody and cannot be null");
            }
            else
            {
                this.Severity = severity;
            }
            this.CustomData = customData;
        }
        
        /// <summary>
        /// Gets or Sets CustomData
        /// </summary>
        [DataMember(Name="customData", EmitDefaultValue=false)]
        public CustomDataType CustomData { get; set; }

        /// <summary>
        /// The Charging Station SHALL only report events with a severity number lower than or equal to this severity.  The severity range is 0-9, with 0 as the highest and 9 as the lowest severity level.    The severity levels have the following meaning: +  *0-Danger* +  Indicates lives are potentially in danger. Urgent attention is needed and action should be taken immediately. +  *1-Hardware Failure* +  Indicates that the Charging Station is unable to continue regular operations due to Hardware issues. Action is required. +  *2-System Failure* +  Indicates that the Charging Station is unable to continue regular operations due to software or minor hardware issues. Action is required. +  *3-Critical* +  Indicates a critical error. Action is required. +  *4-Error* +  Indicates a non-urgent error. Action is required. +  *5-Alert* +  Indicates an alert event. Default severity for any type of monitoring event.  +  *6-Warning* +  Indicates a warning event. Action may be required. +  *7-Notice* +  Indicates an unusual event. No immediate action is required. +  *8-Informational* +  Indicates a regular operational event. May be used for reporting, measuring throughput, etc. No action is required. +  *9-Debug* +  Indicates information useful to developers for debugging, not useful during operations.      
        /// </summary>
        /// <value>The Charging Station SHALL only report events with a severity number lower than or equal to this severity.  The severity range is 0-9, with 0 as the highest and 9 as the lowest severity level.    The severity levels have the following meaning: +  *0-Danger* +  Indicates lives are potentially in danger. Urgent attention is needed and action should be taken immediately. +  *1-Hardware Failure* +  Indicates that the Charging Station is unable to continue regular operations due to Hardware issues. Action is required. +  *2-System Failure* +  Indicates that the Charging Station is unable to continue regular operations due to software or minor hardware issues. Action is required. +  *3-Critical* +  Indicates a critical error. Action is required. +  *4-Error* +  Indicates a non-urgent error. Action is required. +  *5-Alert* +  Indicates an alert event. Default severity for any type of monitoring event.  +  *6-Warning* +  Indicates a warning event. Action may be required. +  *7-Notice* +  Indicates an unusual event. No immediate action is required. +  *8-Informational* +  Indicates a regular operational event. May be used for reporting, measuring throughput, etc. No action is required. +  *9-Debug* +  Indicates information useful to developers for debugging, not useful during operations.      </value>
        [DataMember(Name="severity", EmitDefaultValue=false)]
        public int? Severity { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MonitoringSetMonitoringLevelBody {\n");
            sb.Append("  CustomData: ").Append(CustomData).Append("\n");
            sb.Append("  Severity: ").Append(Severity).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MonitoringSetMonitoringLevelBody);
        }

        /// <summary>
        /// Returns true if MonitoringSetMonitoringLevelBody instances are equal
        /// </summary>
        /// <param name="input">Instance of MonitoringSetMonitoringLevelBody to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MonitoringSetMonitoringLevelBody input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CustomData == input.CustomData ||
                    (this.CustomData != null &&
                    this.CustomData.Equals(input.CustomData))
                ) && 
                (
                    this.Severity == input.Severity ||
                    (this.Severity != null &&
                    this.Severity.Equals(input.Severity))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CustomData != null)
                    hashCode = hashCode * 59 + this.CustomData.GetHashCode();
                if (this.Severity != null)
                    hashCode = hashCode * 59 + this.Severity.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
