/* 
 * CitrineOS Central System API
 *
 * Central System API for OCPP 2.0.1 messaging.
 *
 * OpenAPI spec version: 1.4.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// MonitoringSetVariablesBody
    /// </summary>
    [DataContract]
        public partial class MonitoringSetVariablesBody :  IEquatable<MonitoringSetVariablesBody>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MonitoringSetVariablesBody" /> class.
        /// </summary>
        /// <param name="customData">customData.</param>
        /// <param name="setVariableData">setVariableData (required).</param>
        public MonitoringSetVariablesBody(CustomDataType customData = default(CustomDataType), List<SetVariableDataType> setVariableData = default(List<SetVariableDataType>))
        {
            // to ensure "setVariableData" is required (not null)
            if (setVariableData == null)
            {
                throw new InvalidDataException("setVariableData is a required property for MonitoringSetVariablesBody and cannot be null");
            }
            else
            {
                this.SetVariableData = setVariableData;
            }
            this.CustomData = customData;
        }
        
        /// <summary>
        /// Gets or Sets CustomData
        /// </summary>
        [DataMember(Name="customData", EmitDefaultValue=false)]
        public CustomDataType CustomData { get; set; }

        /// <summary>
        /// Gets or Sets SetVariableData
        /// </summary>
        [DataMember(Name="setVariableData", EmitDefaultValue=false)]
        public List<SetVariableDataType> SetVariableData { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MonitoringSetVariablesBody {\n");
            sb.Append("  CustomData: ").Append(CustomData).Append("\n");
            sb.Append("  SetVariableData: ").Append(SetVariableData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MonitoringSetVariablesBody);
        }

        /// <summary>
        /// Returns true if MonitoringSetVariablesBody instances are equal
        /// </summary>
        /// <param name="input">Instance of MonitoringSetVariablesBody to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MonitoringSetVariablesBody input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CustomData == input.CustomData ||
                    (this.CustomData != null &&
                    this.CustomData.Equals(input.CustomData))
                ) && 
                (
                    this.SetVariableData == input.SetVariableData ||
                    this.SetVariableData != null &&
                    input.SetVariableData != null &&
                    this.SetVariableData.SequenceEqual(input.SetVariableData)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CustomData != null)
                    hashCode = hashCode * 59 + this.CustomData.GetHashCode();
                if (this.SetVariableData != null)
                    hashCode = hashCode * 59 + this.SetVariableData.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
