/* 
 * CitrineOS Central System API
 *
 * Central System API for OCPP 2.0.1 messaging.
 *
 * OpenAPI spec version: 1.4.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// SmartchargingClearedChargingLimitBody
    /// </summary>
    [DataContract]
        public partial class SmartchargingClearedChargingLimitBody :  IEquatable<SmartchargingClearedChargingLimitBody>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SmartchargingClearedChargingLimitBody" /> class.
        /// </summary>
        /// <param name="customData">customData.</param>
        /// <param name="chargingLimitSource">chargingLimitSource (required).</param>
        /// <param name="evseId">EVSE Identifier.  .</param>
        public SmartchargingClearedChargingLimitBody(CustomDataType customData = default(CustomDataType), ChargingLimitSourceEnumType chargingLimitSource = default(ChargingLimitSourceEnumType), int? evseId = default(int?))
        {
            // to ensure "chargingLimitSource" is required (not null)
            if (chargingLimitSource == null)
            {
                throw new InvalidDataException("chargingLimitSource is a required property for SmartchargingClearedChargingLimitBody and cannot be null");
            }
            else
            {
                this.ChargingLimitSource = chargingLimitSource;
            }
            this.CustomData = customData;
            this.EvseId = evseId;
        }
        
        /// <summary>
        /// Gets or Sets CustomData
        /// </summary>
        [DataMember(Name="customData", EmitDefaultValue=false)]
        public CustomDataType CustomData { get; set; }

        /// <summary>
        /// Gets or Sets ChargingLimitSource
        /// </summary>
        [DataMember(Name="chargingLimitSource", EmitDefaultValue=false)]
        public ChargingLimitSourceEnumType ChargingLimitSource { get; set; }

        /// <summary>
        /// EVSE Identifier.  
        /// </summary>
        /// <value>EVSE Identifier.  </value>
        [DataMember(Name="evseId", EmitDefaultValue=false)]
        public int? EvseId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SmartchargingClearedChargingLimitBody {\n");
            sb.Append("  CustomData: ").Append(CustomData).Append("\n");
            sb.Append("  ChargingLimitSource: ").Append(ChargingLimitSource).Append("\n");
            sb.Append("  EvseId: ").Append(EvseId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SmartchargingClearedChargingLimitBody);
        }

        /// <summary>
        /// Returns true if SmartchargingClearedChargingLimitBody instances are equal
        /// </summary>
        /// <param name="input">Instance of SmartchargingClearedChargingLimitBody to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SmartchargingClearedChargingLimitBody input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CustomData == input.CustomData ||
                    (this.CustomData != null &&
                    this.CustomData.Equals(input.CustomData))
                ) && 
                (
                    this.ChargingLimitSource == input.ChargingLimitSource ||
                    (this.ChargingLimitSource != null &&
                    this.ChargingLimitSource.Equals(input.ChargingLimitSource))
                ) && 
                (
                    this.EvseId == input.EvseId ||
                    (this.EvseId != null &&
                    this.EvseId.Equals(input.EvseId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CustomData != null)
                    hashCode = hashCode * 59 + this.CustomData.GetHashCode();
                if (this.ChargingLimitSource != null)
                    hashCode = hashCode * 59 + this.ChargingLimitSource.GetHashCode();
                if (this.EvseId != null)
                    hashCode = hashCode * 59 + this.EvseId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
