/* 
 * CitrineOS Central System API
 *
 * Central System API for OCPP 2.0.1 messaging.
 *
 * OpenAPI spec version: 1.4.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ocpp.citrineos.Api;
using ocpp.citrineos.Model;
using ocpp.citrineos.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CertificatesCertificateSignedBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CertificatesCertificateSignedBodyTests
    {
        // TODO uncomment below to declare an instance variable for CertificatesCertificateSignedBody
        //private CertificatesCertificateSignedBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CertificatesCertificateSignedBody
            //instance = new CertificatesCertificateSignedBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CertificatesCertificateSignedBody
        /// </summary>
        [Test]
        public void CertificatesCertificateSignedBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CertificatesCertificateSignedBody
            //Assert.IsInstanceOfType<CertificatesCertificateSignedBody> (instance, "variable 'instance' is a CertificatesCertificateSignedBody");
        }


        /// <summary>
        /// Test the property 'CustomData'
        /// </summary>
        [Test]
        public void CustomDataTest()
        {
            // TODO unit test for the property 'CustomData'
        }
        /// <summary>
        /// Test the property 'CertificateChain'
        /// </summary>
        [Test]
        public void CertificateChainTest()
        {
            // TODO unit test for the property 'CertificateChain'
        }
        /// <summary>
        /// Test the property 'CertificateType'
        /// </summary>
        [Test]
        public void CertificateTypeTest()
        {
            // TODO unit test for the property 'CertificateType'
        }

    }

}
