/* 
 * CitrineOS Central System API
 *
 * Central System API for OCPP 2.0.1 messaging.
 *
 * OpenAPI spec version: 1.4.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CertificatesGetInstalledCertificateIdsBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CertificatesGetInstalledCertificateIdsBodyTests
    {
        // TODO uncomment below to declare an instance variable for CertificatesGetInstalledCertificateIdsBody
        //private CertificatesGetInstalledCertificateIdsBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CertificatesGetInstalledCertificateIdsBody
            //instance = new CertificatesGetInstalledCertificateIdsBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CertificatesGetInstalledCertificateIdsBody
        /// </summary>
        [Test]
        public void CertificatesGetInstalledCertificateIdsBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CertificatesGetInstalledCertificateIdsBody
            //Assert.IsInstanceOfType<CertificatesGetInstalledCertificateIdsBody> (instance, "variable 'instance' is a CertificatesGetInstalledCertificateIdsBody");
        }


        /// <summary>
        /// Test the property 'CustomData'
        /// </summary>
        [Test]
        public void CustomDataTest()
        {
            // TODO unit test for the property 'CustomData'
        }
        /// <summary>
        /// Test the property 'CertificateType'
        /// </summary>
        [Test]
        public void CertificateTypeTest()
        {
            // TODO unit test for the property 'CertificateType'
        }

    }

}
