/* 
 * CitrineOS Central System API
 *
 * Central System API for OCPP 2.0.1 messaging.
 *
 * OpenAPI spec version: 1.4.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ocpp.citrineos.Api;
using ocpp.citrineos.Model;
using ocpp.citrineos.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CertificatesTlsCertificatesBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CertificatesTlsCertificatesBodyTests
    {
        // TODO uncomment below to declare an instance variable for CertificatesTlsCertificatesBody
        //private CertificatesTlsCertificatesBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CertificatesTlsCertificatesBody
            //instance = new CertificatesTlsCertificatesBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CertificatesTlsCertificatesBody
        /// </summary>
        [Test]
        public void CertificatesTlsCertificatesBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CertificatesTlsCertificatesBody
            //Assert.IsInstanceOfType<CertificatesTlsCertificatesBody> (instance, "variable 'instance' is a CertificatesTlsCertificatesBody");
        }


        /// <summary>
        /// Test the property 'CertificateChain'
        /// </summary>
        [Test]
        public void CertificateChainTest()
        {
            // TODO unit test for the property 'CertificateChain'
        }
        /// <summary>
        /// Test the property 'PrivateKey'
        /// </summary>
        [Test]
        public void PrivateKeyTest()
        {
            // TODO unit test for the property 'PrivateKey'
        }
        /// <summary>
        /// Test the property 'RootCA'
        /// </summary>
        [Test]
        public void RootCATest()
        {
            // TODO unit test for the property 'RootCA'
        }
        /// <summary>
        /// Test the property 'SubCAKey'
        /// </summary>
        [Test]
        public void SubCAKeyTest()
        {
            // TODO unit test for the property 'SubCAKey'
        }

    }

}
