/* 
 * CitrineOS Central System API
 *
 * Central System API for OCPP 2.0.1 messaging.
 *
 * OpenAPI spec version: 1.4.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ocpp.citrineos.Api;
using ocpp.citrineos.Model;
using ocpp.citrineos.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ConfigurationUpdateFirmwareBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ConfigurationUpdateFirmwareBodyTests
    {
        // TODO uncomment below to declare an instance variable for ConfigurationUpdateFirmwareBody
        //private ConfigurationUpdateFirmwareBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ConfigurationUpdateFirmwareBody
            //instance = new ConfigurationUpdateFirmwareBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ConfigurationUpdateFirmwareBody
        /// </summary>
        [Test]
        public void ConfigurationUpdateFirmwareBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ConfigurationUpdateFirmwareBody
            //Assert.IsInstanceOfType<ConfigurationUpdateFirmwareBody> (instance, "variable 'instance' is a ConfigurationUpdateFirmwareBody");
        }


        /// <summary>
        /// Test the property 'CustomData'
        /// </summary>
        [Test]
        public void CustomDataTest()
        {
            // TODO unit test for the property 'CustomData'
        }
        /// <summary>
        /// Test the property 'Retries'
        /// </summary>
        [Test]
        public void RetriesTest()
        {
            // TODO unit test for the property 'Retries'
        }
        /// <summary>
        /// Test the property 'RetryInterval'
        /// </summary>
        [Test]
        public void RetryIntervalTest()
        {
            // TODO unit test for the property 'RetryInterval'
        }
        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Test]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }
        /// <summary>
        /// Test the property 'Firmware'
        /// </summary>
        [Test]
        public void FirmwareTest()
        {
            // TODO unit test for the property 'Firmware'
        }

    }

}
