/* 
 * CitrineOS Central System API
 *
 * Central System API for OCPP 2.0.1 messaging.
 *
 * OpenAPI spec version: 1.4.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing EvdriverSendLocalListBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EvdriverSendLocalListBodyTests
    {
        // TODO uncomment below to declare an instance variable for EvdriverSendLocalListBody
        //private EvdriverSendLocalListBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EvdriverSendLocalListBody
            //instance = new EvdriverSendLocalListBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EvdriverSendLocalListBody
        /// </summary>
        [Test]
        public void EvdriverSendLocalListBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EvdriverSendLocalListBody
            //Assert.IsInstanceOfType<EvdriverSendLocalListBody> (instance, "variable 'instance' is a EvdriverSendLocalListBody");
        }


        /// <summary>
        /// Test the property 'CustomData'
        /// </summary>
        [Test]
        public void CustomDataTest()
        {
            // TODO unit test for the property 'CustomData'
        }
        /// <summary>
        /// Test the property 'LocalAuthorizationList'
        /// </summary>
        [Test]
        public void LocalAuthorizationListTest()
        {
            // TODO unit test for the property 'LocalAuthorizationList'
        }
        /// <summary>
        /// Test the property 'VersionNumber'
        /// </summary>
        [Test]
        public void VersionNumberTest()
        {
            // TODO unit test for the property 'VersionNumber'
        }
        /// <summary>
        /// Test the property 'UpdateType'
        /// </summary>
        [Test]
        public void UpdateTypeTest()
        {
            // TODO unit test for the property 'UpdateType'
        }

    }

}
