/* 
 * CitrineOS Central System API
 *
 * Central System API for OCPP 2.0.1 messaging.
 *
 * OpenAPI spec version: 1.4.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing OcpprouterSubscriptionBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OcpprouterSubscriptionBodyTests
    {
        // TODO uncomment below to declare an instance variable for OcpprouterSubscriptionBody
        //private OcpprouterSubscriptionBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OcpprouterSubscriptionBody
            //instance = new OcpprouterSubscriptionBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OcpprouterSubscriptionBody
        /// </summary>
        [Test]
        public void OcpprouterSubscriptionBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OcpprouterSubscriptionBody
            //Assert.IsInstanceOfType<OcpprouterSubscriptionBody> (instance, "variable 'instance' is a OcpprouterSubscriptionBody");
        }


        /// <summary>
        /// Test the property 'StationId'
        /// </summary>
        [Test]
        public void StationIdTest()
        {
            // TODO unit test for the property 'StationId'
        }
        /// <summary>
        /// Test the property 'OnConnect'
        /// </summary>
        [Test]
        public void OnConnectTest()
        {
            // TODO unit test for the property 'OnConnect'
        }
        /// <summary>
        /// Test the property 'OnClose'
        /// </summary>
        [Test]
        public void OnCloseTest()
        {
            // TODO unit test for the property 'OnClose'
        }
        /// <summary>
        /// Test the property 'OnMessage'
        /// </summary>
        [Test]
        public void OnMessageTest()
        {
            // TODO unit test for the property 'OnMessage'
        }
        /// <summary>
        /// Test the property 'SentMessage'
        /// </summary>
        [Test]
        public void SentMessageTest()
        {
            // TODO unit test for the property 'SentMessage'
        }
        /// <summary>
        /// Test the property 'MessageRegexFilter'
        /// </summary>
        [Test]
        public void MessageRegexFilterTest()
        {
            // TODO unit test for the property 'MessageRegexFilter'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

    }

}
