/* 
 * CitrineOS Central System API
 *
 * Central System API for OCPP 2.0.1 messaging.
 *
 * OpenAPI spec version: 1.4.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ReportingGetLogBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReportingGetLogBodyTests
    {
        // TODO uncomment below to declare an instance variable for ReportingGetLogBody
        //private ReportingGetLogBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReportingGetLogBody
            //instance = new ReportingGetLogBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReportingGetLogBody
        /// </summary>
        [Test]
        public void ReportingGetLogBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReportingGetLogBody
            //Assert.IsInstanceOfType<ReportingGetLogBody> (instance, "variable 'instance' is a ReportingGetLogBody");
        }


        /// <summary>
        /// Test the property 'CustomData'
        /// </summary>
        [Test]
        public void CustomDataTest()
        {
            // TODO unit test for the property 'CustomData'
        }
        /// <summary>
        /// Test the property 'Log'
        /// </summary>
        [Test]
        public void LogTest()
        {
            // TODO unit test for the property 'Log'
        }
        /// <summary>
        /// Test the property 'LogType'
        /// </summary>
        [Test]
        public void LogTypeTest()
        {
            // TODO unit test for the property 'LogType'
        }
        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Test]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }
        /// <summary>
        /// Test the property 'Retries'
        /// </summary>
        [Test]
        public void RetriesTest()
        {
            // TODO unit test for the property 'Retries'
        }
        /// <summary>
        /// Test the property 'RetryInterval'
        /// </summary>
        [Test]
        public void RetryIntervalTest()
        {
            // TODO unit test for the property 'RetryInterval'
        }

    }

}
