/* 
 * CitrineOS Central System API
 *
 * Central System API for OCPP 2.0.1 messaging.
 *
 * OpenAPI spec version: 1.4.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ocpp.citrineos.Api;
using ocpp.citrineos.Model;
using ocpp.citrineos.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SmartchargingClearedChargingLimitBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SmartchargingClearedChargingLimitBodyTests
    {
        // TODO uncomment below to declare an instance variable for SmartchargingClearedChargingLimitBody
        //private SmartchargingClearedChargingLimitBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SmartchargingClearedChargingLimitBody
            //instance = new SmartchargingClearedChargingLimitBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SmartchargingClearedChargingLimitBody
        /// </summary>
        [Test]
        public void SmartchargingClearedChargingLimitBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SmartchargingClearedChargingLimitBody
            //Assert.IsInstanceOfType<SmartchargingClearedChargingLimitBody> (instance, "variable 'instance' is a SmartchargingClearedChargingLimitBody");
        }


        /// <summary>
        /// Test the property 'CustomData'
        /// </summary>
        [Test]
        public void CustomDataTest()
        {
            // TODO unit test for the property 'CustomData'
        }
        /// <summary>
        /// Test the property 'ChargingLimitSource'
        /// </summary>
        [Test]
        public void ChargingLimitSourceTest()
        {
            // TODO unit test for the property 'ChargingLimitSource'
        }
        /// <summary>
        /// Test the property 'EvseId'
        /// </summary>
        [Test]
        public void EvseIdTest()
        {
            // TODO unit test for the property 'EvseId'
        }

    }

}
