/* 
 * CitrineOS Central System API
 *
 * Central System API for OCPP 2.0.1 messaging.
 *
 * OpenAPI spec version: 1.4.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ocpp.citrineos.Api;
using ocpp.citrineos.Model;
using ocpp.citrineos.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ocpp.citrineos.Test
{
    /// <summary>
    ///  Class for testing CertificatesRootCertificateBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CertificatesRootCertificateBodyTests
    {
        // TODO uncomment below to declare an instance variable for CertificatesRootCertificateBody
        //private CertificatesRootCertificateBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CertificatesRootCertificateBody
            //instance = new CertificatesRootCertificateBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CertificatesRootCertificateBody
        /// </summary>
        [Test]
        public void CertificatesRootCertificateBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CertificatesRootCertificateBody
            //Assert.IsInstanceOfType<CertificatesRootCertificateBody> (instance, "variable 'instance' is a CertificatesRootCertificateBody");
        }


        /// <summary>
        /// Test the property 'StationId'
        /// </summary>
        [Test]
        public void StationIdTest()
        {
            // TODO unit test for the property 'StationId'
        }
        /// <summary>
        /// Test the property 'CertificateType'
        /// </summary>
        [Test]
        public void CertificateTypeTest()
        {
            // TODO unit test for the property 'CertificateType'
        }
        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Test]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }
        /// <summary>
        /// Test the property 'CallbackUrl'
        /// </summary>
        [Test]
        public void CallbackUrlTest()
        {
            // TODO unit test for the property 'CallbackUrl'
        }
        /// <summary>
        /// Test the property 'FileId'
        /// </summary>
        [Test]
        public void FileIdTest()
        {
            // TODO unit test for the property 'FileId'
        }

    }

}
