/* 
 * CitrineOS Central System API
 *
 * Central System API for OCPP 2.0.1 messaging.
 *
 * OpenAPI spec version: 1.4.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ocpp.citrineos.Api;
using ocpp.citrineos.Model;
using ocpp.citrineos.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ocpp.citrineos.Test
{
    /// <summary>
    ///  Class for testing CertificatesDeleteCertificateBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CertificatesDeleteCertificateBodyTests
    {
        // TODO uncomment below to declare an instance variable for CertificatesDeleteCertificateBody
        //private CertificatesDeleteCertificateBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CertificatesDeleteCertificateBody
            //instance = new CertificatesDeleteCertificateBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CertificatesDeleteCertificateBody
        /// </summary>
        [Test]
        public void CertificatesDeleteCertificateBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CertificatesDeleteCertificateBody
            //Assert.IsInstanceOfType<CertificatesDeleteCertificateBody> (instance, "variable 'instance' is a CertificatesDeleteCertificateBody");
        }


        /// <summary>
        /// Test the property 'CustomData'
        /// </summary>
        [Test]
        public void CustomDataTest()
        {
            // TODO unit test for the property 'CustomData'
        }
        /// <summary>
        /// Test the property 'CertificateHashData'
        /// </summary>
        [Test]
        public void CertificateHashDataTest()
        {
            // TODO unit test for the property 'CertificateHashData'
        }

    }

}
