/* 
 * CitrineOS Central System API
 *
 * Central System API for OCPP 2.0.1 messaging.
 *
 * OpenAPI spec version: 1.4.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ocpp.citrineos.Api;
using ocpp.citrineos.Model;
using ocpp.citrineos.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ocpp.citrineos.Test
{
    /// <summary>
    ///  Class for testing ConfigurationSetNetworkProfileBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ConfigurationSetNetworkProfileBodyTests
    {
        // TODO uncomment below to declare an instance variable for ConfigurationSetNetworkProfileBody
        //private ConfigurationSetNetworkProfileBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ConfigurationSetNetworkProfileBody
            //instance = new ConfigurationSetNetworkProfileBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ConfigurationSetNetworkProfileBody
        /// </summary>
        [Test]
        public void ConfigurationSetNetworkProfileBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ConfigurationSetNetworkProfileBody
            //Assert.IsInstanceOfType<ConfigurationSetNetworkProfileBody> (instance, "variable 'instance' is a ConfigurationSetNetworkProfileBody");
        }


        /// <summary>
        /// Test the property 'CustomData'
        /// </summary>
        [Test]
        public void CustomDataTest()
        {
            // TODO unit test for the property 'CustomData'
        }
        /// <summary>
        /// Test the property 'ConfigurationSlot'
        /// </summary>
        [Test]
        public void ConfigurationSlotTest()
        {
            // TODO unit test for the property 'ConfigurationSlot'
        }
        /// <summary>
        /// Test the property 'ConnectionData'
        /// </summary>
        [Test]
        public void ConnectionDataTest()
        {
            // TODO unit test for the property 'ConnectionData'
        }

    }

}
