/* 
 * CitrineOS Central System API
 *
 * Central System API for OCPP 2.0.1 messaging.
 *
 * OpenAPI spec version: 1.4.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ocpp.citrineos.Api;
using ocpp.citrineos.Model;
using ocpp.citrineos.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ocpp.citrineos.Test
{
    /// <summary>
    ///  Class for testing ConfigurationResetBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ConfigurationResetBodyTests
    {
        // TODO uncomment below to declare an instance variable for ConfigurationResetBody
        //private ConfigurationResetBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ConfigurationResetBody
            //instance = new ConfigurationResetBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ConfigurationResetBody
        /// </summary>
        [Test]
        public void ConfigurationResetBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ConfigurationResetBody
            //Assert.IsInstanceOfType<ConfigurationResetBody> (instance, "variable 'instance' is a ConfigurationResetBody");
        }


        /// <summary>
        /// Test the property 'CustomData'
        /// </summary>
        [Test]
        public void CustomDataTest()
        {
            // TODO unit test for the property 'CustomData'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'EvseId'
        /// </summary>
        [Test]
        public void EvseIdTest()
        {
            // TODO unit test for the property 'EvseId'
        }

    }

}
