/* 
 * CitrineOS Central System API
 *
 * Central System API for OCPP 2.0.1 messaging.
 *
 * OpenAPI spec version: 1.4.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ocpp.citrineos.Api;
using ocpp.citrineos.Model;
using ocpp.citrineos.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ocpp.citrineos.Test
{
    /// <summary>
    ///  Class for testing ConfigurationBootBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ConfigurationBootBodyTests
    {
        // TODO uncomment below to declare an instance variable for ConfigurationBootBody
        //private ConfigurationBootBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ConfigurationBootBody
            //instance = new ConfigurationBootBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ConfigurationBootBody
        /// </summary>
        [Test]
        public void ConfigurationBootBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ConfigurationBootBody
            //Assert.IsInstanceOfType<ConfigurationBootBody> (instance, "variable 'instance' is a ConfigurationBootBody");
        }


        /// <summary>
        /// Test the property 'HeartbeatInterval'
        /// </summary>
        [Test]
        public void HeartbeatIntervalTest()
        {
            // TODO unit test for the property 'HeartbeatInterval'
        }
        /// <summary>
        /// Test the property 'BootRetryInterval'
        /// </summary>
        [Test]
        public void BootRetryIntervalTest()
        {
            // TODO unit test for the property 'BootRetryInterval'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'StatusInfo'
        /// </summary>
        [Test]
        public void StatusInfoTest()
        {
            // TODO unit test for the property 'StatusInfo'
        }
        /// <summary>
        /// Test the property 'GetBaseReportOnPending'
        /// </summary>
        [Test]
        public void GetBaseReportOnPendingTest()
        {
            // TODO unit test for the property 'GetBaseReportOnPending'
        }
        /// <summary>
        /// Test the property 'SetVariableIds'
        /// </summary>
        [Test]
        public void SetVariableIdsTest()
        {
            // TODO unit test for the property 'SetVariableIds'
        }
        /// <summary>
        /// Test the property 'BootWithRejectedVariables'
        /// </summary>
        [Test]
        public void BootWithRejectedVariablesTest()
        {
            // TODO unit test for the property 'BootWithRejectedVariables'
        }

    }

}
