/* 
 * CitrineOS Central System API
 *
 * Central System API for OCPP 2.0.1 messaging.
 *
 * OpenAPI spec version: 1.4.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ocpp.citrineos.Api;
using ocpp.citrineos.Model;
using ocpp.citrineos.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ocpp.citrineos.Test
{
    /// <summary>
    ///  Class for testing EvdriverAuthorizationBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EvdriverAuthorizationBodyTests
    {
        // TODO uncomment below to declare an instance variable for EvdriverAuthorizationBody
        //private EvdriverAuthorizationBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EvdriverAuthorizationBody
            //instance = new EvdriverAuthorizationBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EvdriverAuthorizationBody
        /// </summary>
        [Test]
        public void EvdriverAuthorizationBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EvdriverAuthorizationBody
            //Assert.IsInstanceOfType<EvdriverAuthorizationBody> (instance, "variable 'instance' is a EvdriverAuthorizationBody");
        }


        /// <summary>
        /// Test the property 'IdToken'
        /// </summary>
        [Test]
        public void IdTokenTest()
        {
            // TODO unit test for the property 'IdToken'
        }
        /// <summary>
        /// Test the property 'IdTokenInfo'
        /// </summary>
        [Test]
        public void IdTokenInfoTest()
        {
            // TODO unit test for the property 'IdTokenInfo'
        }

    }

}
