/* 
 * CitrineOS Central System API
 *
 * Central System API for OCPP 2.0.1 messaging.
 *
 * OpenAPI spec version: 1.4.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ocpp.citrineos.Api;
using ocpp.citrineos.Model;
using ocpp.citrineos.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ocpp.citrineos.Test
{
    /// <summary>
    ///  Class for testing MonitoringVariableAttributeBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MonitoringVariableAttributeBodyTests
    {
        // TODO uncomment below to declare an instance variable for MonitoringVariableAttributeBody
        //private MonitoringVariableAttributeBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MonitoringVariableAttributeBody
            //instance = new MonitoringVariableAttributeBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MonitoringVariableAttributeBody
        /// </summary>
        [Test]
        public void MonitoringVariableAttributeBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MonitoringVariableAttributeBody
            //Assert.IsInstanceOfType<MonitoringVariableAttributeBody> (instance, "variable 'instance' is a MonitoringVariableAttributeBody");
        }


        /// <summary>
        /// Test the property 'Component'
        /// </summary>
        [Test]
        public void ComponentTest()
        {
            // TODO unit test for the property 'Component'
        }
        /// <summary>
        /// Test the property 'Variable'
        /// </summary>
        [Test]
        public void VariableTest()
        {
            // TODO unit test for the property 'Variable'
        }
        /// <summary>
        /// Test the property 'VariableAttribute'
        /// </summary>
        [Test]
        public void VariableAttributeTest()
        {
            // TODO unit test for the property 'VariableAttribute'
        }
        /// <summary>
        /// Test the property 'VariableCharacteristics'
        /// </summary>
        [Test]
        public void VariableCharacteristicsTest()
        {
            // TODO unit test for the property 'VariableCharacteristics'
        }

    }

}
