/* 
 * CitrineOS Central System API
 *
 * Central System API for OCPP 2.0.1 messaging.
 *
 * OpenAPI spec version: 1.4.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ocpp.citrineos.Api;
using ocpp.citrineos.Model;
using ocpp.citrineos.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ocpp.citrineos.Test
{
    /// <summary>
    ///  Class for testing ReportingGetMonitoringReportBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReportingGetMonitoringReportBodyTests
    {
        // TODO uncomment below to declare an instance variable for ReportingGetMonitoringReportBody
        //private ReportingGetMonitoringReportBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReportingGetMonitoringReportBody
            //instance = new ReportingGetMonitoringReportBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReportingGetMonitoringReportBody
        /// </summary>
        [Test]
        public void ReportingGetMonitoringReportBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReportingGetMonitoringReportBody
            //Assert.IsInstanceOfType<ReportingGetMonitoringReportBody> (instance, "variable 'instance' is a ReportingGetMonitoringReportBody");
        }


        /// <summary>
        /// Test the property 'CustomData'
        /// </summary>
        [Test]
        public void CustomDataTest()
        {
            // TODO unit test for the property 'CustomData'
        }
        /// <summary>
        /// Test the property 'ComponentVariable'
        /// </summary>
        [Test]
        public void ComponentVariableTest()
        {
            // TODO unit test for the property 'ComponentVariable'
        }
        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Test]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }
        /// <summary>
        /// Test the property 'MonitoringCriteria'
        /// </summary>
        [Test]
        public void MonitoringCriteriaTest()
        {
            // TODO unit test for the property 'MonitoringCriteria'
        }

    }

}
