/* 
 * CitrineOS Central System API
 *
 * Central System API for OCPP 2.0.1 messaging.
 *
 * OpenAPI spec version: 1.4.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ocpp.citrineos.Api;
using ocpp.citrineos.Model;
using ocpp.citrineos.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ocpp.citrineos.Test
{
    /// <summary>
    ///  Class for testing SmartchargingGetCompositeScheduleBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SmartchargingGetCompositeScheduleBodyTests
    {
        // TODO uncomment below to declare an instance variable for SmartchargingGetCompositeScheduleBody
        //private SmartchargingGetCompositeScheduleBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SmartchargingGetCompositeScheduleBody
            //instance = new SmartchargingGetCompositeScheduleBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SmartchargingGetCompositeScheduleBody
        /// </summary>
        [Test]
        public void SmartchargingGetCompositeScheduleBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SmartchargingGetCompositeScheduleBody
            //Assert.IsInstanceOfType<SmartchargingGetCompositeScheduleBody> (instance, "variable 'instance' is a SmartchargingGetCompositeScheduleBody");
        }


        /// <summary>
        /// Test the property 'CustomData'
        /// </summary>
        [Test]
        public void CustomDataTest()
        {
            // TODO unit test for the property 'CustomData'
        }
        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Test]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }
        /// <summary>
        /// Test the property 'ChargingRateUnit'
        /// </summary>
        [Test]
        public void ChargingRateUnitTest()
        {
            // TODO unit test for the property 'ChargingRateUnit'
        }
        /// <summary>
        /// Test the property 'EvseId'
        /// </summary>
        [Test]
        public void EvseIdTest()
        {
            // TODO unit test for the property 'EvseId'
        }

    }

}
