/* 
 * MaEVe CSMS
 *
 * Internal API to interact with the MaEVe CSMS, external clients should use OCPI.
 *
 * OpenAPI spec version: 0.0.0
 * Contact: maeve-team@thoughtworks.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// The set of certificates to install on the charge station. The certificates will be sent to the charge station asynchronously. 
    /// </summary>
    [DataContract]
        public partial class ChargeStationInstallCertificates :  IEquatable<ChargeStationInstallCertificates>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ChargeStationInstallCertificates" /> class.
        /// </summary>
        /// <param name="certificates">certificates (required).</param>
        public ChargeStationInstallCertificates(List<ChargeStationInstallCertificatesCertificates> certificates = default(List<ChargeStationInstallCertificatesCertificates>))
        {
            // to ensure "certificates" is required (not null)
            if (certificates == null)
            {
                throw new InvalidDataException("certificates is a required property for ChargeStationInstallCertificates and cannot be null");
            }
            else
            {
                this.Certificates = certificates;
            }
        }
        
        /// <summary>
        /// Gets or Sets Certificates
        /// </summary>
        [DataMember(Name="certificates", EmitDefaultValue=false)]
        public List<ChargeStationInstallCertificatesCertificates> Certificates { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ChargeStationInstallCertificates {\n");
            sb.Append("  Certificates: ").Append(Certificates).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ChargeStationInstallCertificates);
        }

        /// <summary>
        /// Returns true if ChargeStationInstallCertificates instances are equal
        /// </summary>
        /// <param name="input">Instance of ChargeStationInstallCertificates to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ChargeStationInstallCertificates input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Certificates == input.Certificates ||
                    this.Certificates != null &&
                    input.Certificates != null &&
                    this.Certificates.SequenceEqual(input.Certificates)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Certificates != null)
                    hashCode = hashCode * 59 + this.Certificates.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
