/* 
 * CitrineOS Central System API
 *
 * Central System API for OCPP 2.0.1 messaging.
 *
 * OpenAPI spec version: 1.4.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ocpp.citrineos.Client.SwaggerDateConverter;
namespace ocpp.citrineos.Model
{
    /// <summary>
    /// MonitoringGetVariablesBody
    /// </summary>
    [DataContract]
        public partial class MonitoringGetVariablesBody :  IEquatable<MonitoringGetVariablesBody>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MonitoringGetVariablesBody" /> class.
        /// </summary>
        /// <param name="customData">customData.</param>
        /// <param name="getVariableData">getVariableData (required).</param>
        public MonitoringGetVariablesBody(CustomDataType customData = default(CustomDataType), List<GetVariableDataType> getVariableData = default(List<GetVariableDataType>))
        {
            // to ensure "getVariableData" is required (not null)
            if (getVariableData == null)
            {
                throw new InvalidDataException("getVariableData is a required property for MonitoringGetVariablesBody and cannot be null");
            }
            else
            {
                this.GetVariableData = getVariableData;
            }
            this.CustomData = customData;
        }
        
        /// <summary>
        /// Gets or Sets CustomData
        /// </summary>
        [DataMember(Name="customData", EmitDefaultValue=false)]
        public CustomDataType CustomData { get; set; }

        /// <summary>
        /// Gets or Sets GetVariableData
        /// </summary>
        [DataMember(Name="getVariableData", EmitDefaultValue=false)]
        public List<GetVariableDataType> GetVariableData { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MonitoringGetVariablesBody {\n");
            sb.Append("  CustomData: ").Append(CustomData).Append("\n");
            sb.Append("  GetVariableData: ").Append(GetVariableData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MonitoringGetVariablesBody);
        }

        /// <summary>
        /// Returns true if MonitoringGetVariablesBody instances are equal
        /// </summary>
        /// <param name="input">Instance of MonitoringGetVariablesBody to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MonitoringGetVariablesBody input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CustomData == input.CustomData ||
                    (this.CustomData != null &&
                    this.CustomData.Equals(input.CustomData))
                ) && 
                (
                    this.GetVariableData == input.GetVariableData ||
                    this.GetVariableData != null &&
                    input.GetVariableData != null &&
                    this.GetVariableData.SequenceEqual(input.GetVariableData)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CustomData != null)
                    hashCode = hashCode * 59 + this.CustomData.GetHashCode();
                if (this.GetVariableData != null)
                    hashCode = hashCode * 59 + this.GetVariableData.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
