/* 
 * MaEVe CSMS
 *
 * Internal API to interact with the MaEVe CSMS, external clients should use OCPI.
 *
 * OpenAPI spec version: 0.0.0
 * Contact: maeve-team@thoughtworks.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ocpp.maeve.Api;
using ocpp.maeve.Model;
using ocpp.maeve.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ocpp.maeve.Test
{
    /// <summary>
    ///  Class for testing Evse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EvseTests
    {
        // TODO uncomment below to declare an instance variable for Evse
        //private Evse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Evse
            //instance = new Evse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Evse
        /// </summary>
        [Test]
        public void EvseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Evse
            //Assert.IsInstanceOfType<Evse> (instance, "variable 'instance' is a Evse");
        }


        /// <summary>
        /// Test the property 'Uid'
        /// </summary>
        [Test]
        public void UidTest()
        {
            // TODO unit test for the property 'Uid'
        }
        /// <summary>
        /// Test the property 'EvseId'
        /// </summary>
        [Test]
        public void EvseIdTest()
        {
            // TODO unit test for the property 'EvseId'
        }
        /// <summary>
        /// Test the property 'Connectors'
        /// </summary>
        [Test]
        public void ConnectorsTest()
        {
            // TODO unit test for the property 'Connectors'
        }

    }

}
