/* 
 * MaEVe CSMS
 *
 * Internal API to interact with the MaEVe CSMS, external clients should use OCPI.
 *
 * OpenAPI spec version: 0.0.0
 * Contact: maeve-team@thoughtworks.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ocpp.maeve.Api;
using ocpp.maeve.Model;
using ocpp.maeve.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ocpp.maeve.Test
{
    /// <summary>
    ///  Class for testing GeoLocation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GeoLocationTests
    {
        // TODO uncomment below to declare an instance variable for GeoLocation
        //private GeoLocation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GeoLocation
            //instance = new GeoLocation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GeoLocation
        /// </summary>
        [Test]
        public void GeoLocationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GeoLocation
            //Assert.IsInstanceOfType<GeoLocation> (instance, "variable 'instance' is a GeoLocation");
        }


        /// <summary>
        /// Test the property 'Latitude'
        /// </summary>
        [Test]
        public void LatitudeTest()
        {
            // TODO unit test for the property 'Latitude'
        }
        /// <summary>
        /// Test the property 'Longitude'
        /// </summary>
        [Test]
        public void LongitudeTest()
        {
            // TODO unit test for the property 'Longitude'
        }

    }

}
